#!/bin/bash
set -e

CURRENT_DIR=$(pwd)

if [[ -z $1 ]];
then
    echo "{!} Vacuum not specified"
    echo "{?} Usage: ./vcondensate vacuum"
    exit 1
fi

if [[ $1 = *.vac ]]; then
    source $CURRENT_DIR/vacuums/$1
else
    source $CURRENT_DIR/vacuums/$1.vac
fi
spacedir="${voidname}-${voidver}_${voidrev}"
export SPACEDIR=$spacedir
exit 0

echo "{#} Checking for dependencies"
if [[ -n $voidbuilddeps ]];
then
    mkdir tmp
    cd tmp
    wget https://github.com/0-linux/zero-voids/raw/refs/heads/main/voidlist.db
    for dep in $voidbuilddeps;
    do
        echo "{#} Installing dependencie ${dep}"
        IFS=":" read -r depname depdeps depsha deppath <<< $(cat voidlist.db | grep $dep)
        wget https://github.com/0-linux/zero-voids/raw/refs/heads/main/$deppath/$depname.void
        if [[ $(sha256sum $dep.void | awk '{ print $1 }') != $depsha ]];
        then
            echo "{!} Checksums do not match!"
            echo "{#} Cleaning after failed condensating"
            cd ..
            rm -rf tmp
            exit 1
        fi
        sudo tar xf $dep.void -C /
    done
    cd ..
    rm -rf tmp
fi

DESTDIR="$CURRENT_DIR/$voidname"
mkdir $DESTDIR

voidfile=$(basename $voidurl)
voiddir="${voidfile%.tar.gz}"
voiddir="${voiddir%.tar.xz}"
voiddir="${voiddir%.tar.bz2}"
voiddir="${voiddir%.tgz}"
voiddir="${voiddir%.zip}"

echo "{#} Cloning ${voidurl}"
wget $voidurl

echo "{#} Verifying sha256 sums"
if [[ $(sha256sum $voidfile | awk '{ print $1 }') != $voidsum ]];
then
    echo "{!} Checksums do not match!"
    echo "{#} Cleaning after failed condensating"
    rm $voidfile
    exit 1
fi

echo "{#} Unpacking $voidfile"
tar xf $voidfile
cd $voiddir

echo "{#} Building void ${voidname}"
build_void

echo "{#} Installing void ${voidname} to ${DESTDIR}"
install_void

echo "{#} Condensating to .void"
cd ../$voidname
tar cf ../$voidname.void *
cd ..

echo "{#} Making space for void"
mkdir "$spacedir"
cd "$spacedir"
mv ../$voidname.void ./
voidsum=$(sha256sum ./$voidname.void | awk '{ print $1 }')
echo "$voidname:$voiddeps:$voidsum:spaces/$spacedir" > $voidname.vdata

echo "{#} Cleaning after vacuum condensating"
cd ..
rm $voidfile
rm -rf $voiddir
rm -rf $DESTDIR


echo "{+} Void ${voidname} condensation successfull!"
