name: Condensate vacuum
run-name: condensate-vacuum
on: 
  workflow_dispatch:
    inputs:
      vacuum-name:
        description: 'Vacuum name'
        type: string
  workflow_call:
jobs:
  condensate:
    runs-on: ubuntu-latest
    steps:
      - name: Condensate ${{ inputs.vacuum-name }}
        uses: actions/checkout@v6
        run: ./vcondensate ${{ inputs.vacuum-name }}
      
      - name: Push to voids
        run: |
          git clone https://github.com/0-linux/zero-voids voids
          cd voids
          ls
