name: Condensate all vacuums
run-name: condensate-all-vacuums
on: 
  workflow_dispatch:
  workflow_call:
jobs:
  condensate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Clone voids repo
        run: git clone https://x-access-token:${{ secrets.VOID_PUSH_TOKEN }}@github.com/0-linux/zero-voids.git voids

      - name: Condensate all
        run: |
          for vac in vacuums/*;
          do
            vac=$(basename $vac)
            vac=${vac%.vac}
            echo "{#} Condensating vacuum $vac"
            ./vcondensate $vac
            DIR=$(ls | grep $vac)
            mkdir -p ./voids/spaces
            rm -rf ./voids/spaces/$DIR
            mv $DIR ./voids/spaces/
          done
      
      - name: Push to voids
        run: |
          git config --global user.name "Zero linux vacuum condensator"
          git config --global user.email "zero-condensator@zerolinux.dpdns.org"
          cd voids
          git add .
          git commit -m "Automatically updated/added all vacuums"
          git push -u origin main
