name: Condensate all vacuums
run-name: condensate-all-vacuums
on: 
  workflow_dispatch:
  workflow_call:
jobs:
  condensate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Clone voids repo
        run: git clone https://x-access-token:${{ secrets.VOID_PUSH_TOKEN }}@github.com/0-linux/zero-voids.git voids

      - name: Condensate all
        run: |
          for vac in vacuums/*;
          do
            echo "{#} Condensating vacuum $(basename $vac)"
            ./vcondensate $(basename $vac)
            DIR=$(ls | grep $vac)
            echo $DIR
            mkdir -p ./voids/spaces
            mv $DIR ./voids/spaces/
          done
          exit 0
      
      - name: Push to voids
        run: |
          ls ./voids/spaces/
          exit 0
          git config --global user.name "Zero linux vacuum condensator"
          git config --global user.email "zero-condensator@zerolinux.dpdns.org"
          DIR=$(ls | grep ${{ inputs.vacuum-name }})
          mkdir ./voids/spaces/ -p
          mv ./$DIR ./voids/spaces/$DIR
          cd voids
          git add .
          git commit -m "Automatically updated/added vacuum ${{ inputs.vacuum-name }}"
          git push -u origin main
