name: Condensate all vacuums
run-name: condensate-all-vacuums
on: 
  workflow_dispatch:
  workflow_call:
jobs:
  condensate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Condensate all
        env:
          SSH_KEY: ${{ secrets.SF_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan frs.sourceforge.net >> ~/.ssh/known_hosts

          for vac in vacuums/*;
          do
            vac=$(basename $vac)
            vac=${vac%.vac}
            echo "{#} Condensating vacuum $vac"
            ./vcondensate $vac
            DIR=$(ls | grep $vac)
            scp -r $DIR aevod@frs.sourceforge.net:/home/frs/project/zero-linux/spaces/
          done
